// Generated by `alicorn theme compile`; do not edit.
package main

import alicorn "alicorn:runtime"

// Returns owned token/binding slices. Call scratchpad_cool_light_theme_destroy after registration.
scratchpad_cool_light_theme :: proc(allocator := context.allocator) -> alicorn.Style_Theme {
    result := alicorn.DEFAULT_STYLE_THEME
    result.colors = {
        alicorn.Color{0.807345927, 0.848088264, 0.911407471, 1},
        alicorn.Color{0.955104589, 0.977401912, 1, 1},
        alicorn.Color{0.72934711, 0.787412286, 0.868899405, 1},
        alicorn.Color{1, 0.988663316, 0.944068372, 1},
        alicorn.Color{0.00598105974, 0.0100228256, 0.019606648, 1},
        alicorn.Color{0.0592535213, 0.0889815241, 0.139984891, 1},
        alicorn.Color{0, 0.094629623, 0.433879524, 1},
        alicorn.Color{0, 0.0592535213, 0.28464669, 1},
        alicorn.Color{0, 0.0363064855, 0.170644939, 1},
        alicorn.Color{1, 1, 1, 1},
        alicorn.Color{0.187316671, 0.447988421, 0.827570856, 0.479999989},
        alicorn.Color{0, 0.0637237951, 0.476999789, 1},
        alicorn.Color{0.119280189, 0.0219809469, 0.34239164, 1},
        alicorn.Color{0.125967383, 0.187316671, 0.273838431, 1},
        alicorn.Color{0.406448305, 0.0134117492, 0.0100228256, 1},
        alicorn.Color{0.00719440915, 0.125967383, 0.0331047662, 1},
        alicorn.Color{0.673859537, 0.748414099, 0.827570856, 1},
        alicorn.Color{0.147319004, 0.223413989, 0.330343723, 1},
    }
    result.color_tokens = make([]alicorn.Color, 37, allocator)
    result.color_tokens[0] = alicorn.Color{0.270000011, 0.479999989, 0.699999988, 1}
    result.color_tokens[1] = alicorn.Color{0.330000013, 0.569999993, 0.800000012, 1}
    result.color_tokens[2] = alicorn.Color{0.360000014, 0.620000005, 0.860000014, 1}
    result.color_tokens[3] = alicorn.Color{0.939999998, 0.970000029, 1, 1}
    result.color_tokens[4] = alicorn.Color{0.200000003, 0.239999995, 0.310000002, 1}
    result.color_tokens[5] = alicorn.Color{0.550000012, 0.180000007, 0.200000003, 1}
    result.color_tokens[6] = alicorn.Color{0.0399999991, 0.0500000007, 0.0700000003, 1}
    result.color_tokens[7] = alicorn.Color{0.75999999, 0.860000014, 1, 1}
    result.color_tokens[8] = alicorn.Color{0.569999993, 0.629999995, 0.74000001, 1}
    result.color_tokens[9] = alicorn.Color{0.379999995, 0.479999989, 0.620000005, 1}
    result.color_tokens[10] = alicorn.Color{0.0799999982, 0.100000001, 0.140000001, 1}
    result.color_tokens[11] = alicorn.Color{0.200000003, 0.419999987, 0.779999971, 0.449999988}
    result.color_tokens[12] = alicorn.Color{0.119999997, 0.779999971, 0.819999993, 1}
    result.color_tokens[13] = alicorn.Color{0.0799999982, 0.100000001, 0.140000001, 1}
    result.color_tokens[14] = alicorn.Color{0.170000002, 0.389999986, 0.340000004, 1}
    result.color_tokens[15] = alicorn.Color{0.0799999982, 0.0949999988, 0.129999995, 1}
    result.color_tokens[16] = alicorn.Color{0.879999995, 0.910000026, 0.959999979, 1}
    result.color_tokens[17] = alicorn.Color{0.0549999997, 0.0649999976, 0.0900000036, 1}
    result.color_tokens[18] = alicorn.Color{0, 0.094629623, 0.433879524, 1}
    result.color_tokens[19] = alicorn.Color{0, 0.0592535213, 0.28464669, 1}
    result.color_tokens[20] = alicorn.Color{0, 0.0363064855, 0.170644939, 1}
    result.color_tokens[21] = alicorn.Color{1, 1, 1, 1}
    result.color_tokens[22] = alicorn.Color{0.125967383, 0.187316671, 0.273838431, 1}
    result.color_tokens[23] = alicorn.Color{0.406448305, 0.0134117492, 0.0100228256, 1}
    result.color_tokens[24] = alicorn.Color{1, 0.988663316, 0.944068372, 1}
    result.color_tokens[25] = alicorn.Color{0, 0.0637237951, 0.476999789, 1}
    result.color_tokens[26] = alicorn.Color{0.0592535213, 0.0889815241, 0.139984891, 1}
    result.color_tokens[27] = alicorn.Color{1, 0.988663316, 0.944068372, 1}
    result.color_tokens[28] = alicorn.Color{0.147319004, 0.223413989, 0.330343723, 1}
    result.color_tokens[29] = alicorn.Color{0.673859537, 0.748414099, 0.827570856, 1}
    result.color_tokens[30] = alicorn.Color{0.187316671, 0.447988421, 0.827570856, 0.479999989}
    result.color_tokens[31] = alicorn.Color{0.119280189, 0.0219809469, 0.34239164, 1}
    result.color_tokens[32] = alicorn.Color{0.72934711, 0.787412286, 0.868899405, 1}
    result.color_tokens[33] = alicorn.Color{0.00719440915, 0.125967383, 0.0331047662, 1}
    result.color_tokens[34] = alicorn.Color{0.955104589, 0.977401912, 1, 1}
    result.color_tokens[35] = alicorn.Color{0.00598105974, 0.0100228256, 0.019606648, 1}
    result.color_tokens[36] = alicorn.Color{0.807345927, 0.848088264, 0.911407471, 1}
    result.core_color_tokens = {
        alicorn.Style_Color_Token_ID(37),
        alicorn.Style_Color_Token_ID(35),
        alicorn.Style_Color_Token_ID(33),
        alicorn.Style_Color_Token_ID(25),
        alicorn.Style_Color_Token_ID(36),
        alicorn.Style_Color_Token_ID(27),
        alicorn.Style_Color_Token_ID(19),
        alicorn.Style_Color_Token_ID(20),
        alicorn.Style_Color_Token_ID(21),
        alicorn.Style_Color_Token_ID(22),
        alicorn.Style_Color_Token_ID(31),
        alicorn.Style_Color_Token_ID(26),
        alicorn.Style_Color_Token_ID(32),
        alicorn.Style_Color_Token_ID(23),
        alicorn.Style_Color_Token_ID(24),
        alicorn.Style_Color_Token_ID(34),
        alicorn.Style_Color_Token_ID(30),
        alicorn.Style_Color_Token_ID(29),
    }
    result.length_tokens = make([]alicorn.Style_Length, 1, allocator)
    result.length_tokens[0] = alicorn.Style_Length{logical_units=10}
    result.extension_color_roles = make([]alicorn.Style_Extension_Color_Role_Binding, 1, allocator)
    result.extension_color_roles[0] = alicorn.Style_Extension_Color_Role_Binding{
        role=alicorn.Style_Extension_Color_Role_ID(u64(7926949792708367841)),
        token=alicorn.Style_Color_Token_ID(28),
    }
    result.extension_length_roles = make([]alicorn.Style_Extension_Length_Role_Binding, 1, allocator)
    result.extension_length_roles[0] = alicorn.Style_Extension_Length_Role_Binding{
        role=alicorn.Style_Extension_Length_Role_ID(u64(1169174812364479353)),
        token=alicorn.Style_Length_Token_ID(1),
    }
    result.color_token_provenance = make([]alicorn.Style_Token_Provenance, 37, allocator)
    result.color_token_provenance[0] = alicorn.Style_Token_Provenance{id=1, name="alicorn.color.accent", alias_target=""}
    result.color_token_provenance[1] = alicorn.Style_Token_Provenance{id=2, name="alicorn.color.accent_hover", alias_target=""}
    result.color_token_provenance[2] = alicorn.Style_Token_Provenance{id=3, name="alicorn.color.accent_pressed", alias_target=""}
    result.color_token_provenance[3] = alicorn.Style_Token_Provenance{id=4, name="alicorn.color.accent_text", alias_target=""}
    result.color_token_provenance[4] = alicorn.Style_Token_Provenance{id=5, name="alicorn.color.border", alias_target=""}
    result.color_token_provenance[5] = alicorn.Style_Token_Provenance{id=6, name="alicorn.color.danger", alias_target=""}
    result.color_token_provenance[6] = alicorn.Style_Token_Provenance{id=7, name="alicorn.color.editor_background", alias_target=""}
    result.color_token_provenance[7] = alicorn.Style_Token_Provenance{id=8, name="alicorn.color.focus", alias_target=""}
    result.color_token_provenance[8] = alicorn.Style_Token_Provenance{id=9, name="alicorn.color.muted_text", alias_target=""}
    result.color_token_provenance[9] = alicorn.Style_Token_Provenance{id=10, name="alicorn.color.scrollbar_thumb", alias_target=""}
    result.color_token_provenance[10] = alicorn.Style_Token_Provenance{id=11, name="alicorn.color.scrollbar_track", alias_target=""}
    result.color_token_provenance[11] = alicorn.Style_Token_Provenance{id=12, name="alicorn.color.selection", alias_target=""}
    result.color_token_provenance[12] = alicorn.Style_Token_Provenance{id=13, name="alicorn.color.semantic_focus", alias_target=""}
    result.color_token_provenance[13] = alicorn.Style_Token_Provenance{id=14, name="alicorn.color.subtle_surface", alias_target=""}
    result.color_token_provenance[14] = alicorn.Style_Token_Provenance{id=15, name="alicorn.color.success", alias_target=""}
    result.color_token_provenance[15] = alicorn.Style_Token_Provenance{id=16, name="alicorn.color.surface", alias_target=""}
    result.color_token_provenance[16] = alicorn.Style_Token_Provenance{id=17, name="alicorn.color.text", alias_target=""}
    result.color_token_provenance[17] = alicorn.Style_Token_Provenance{id=18, name="alicorn.color.window_background", alias_target=""}
    result.color_token_provenance[18] = alicorn.Style_Token_Provenance{id=19, name="scratchpad.cool.accent", alias_target=""}
    result.color_token_provenance[19] = alicorn.Style_Token_Provenance{id=20, name="scratchpad.cool.accent_hover", alias_target=""}
    result.color_token_provenance[20] = alicorn.Style_Token_Provenance{id=21, name="scratchpad.cool.accent_pressed", alias_target=""}
    result.color_token_provenance[21] = alicorn.Style_Token_Provenance{id=22, name="scratchpad.cool.accent_text", alias_target=""}
    result.color_token_provenance[22] = alicorn.Style_Token_Provenance{id=23, name="scratchpad.cool.border", alias_target=""}
    result.color_token_provenance[23] = alicorn.Style_Token_Provenance{id=24, name="scratchpad.cool.danger", alias_target=""}
    result.color_token_provenance[24] = alicorn.Style_Token_Provenance{id=25, name="scratchpad.cool.editor_background", alias_target=""}
    result.color_token_provenance[25] = alicorn.Style_Token_Provenance{id=26, name="scratchpad.cool.focus", alias_target=""}
    result.color_token_provenance[26] = alicorn.Style_Token_Provenance{id=27, name="scratchpad.cool.muted_text", alias_target=""}
    result.color_token_provenance[27] = alicorn.Style_Token_Provenance{id=28, name="scratchpad.cool.paper_surface", alias_target="scratchpad.cool.editor_background"}
    result.color_token_provenance[28] = alicorn.Style_Token_Provenance{id=29, name="scratchpad.cool.scrollbar_thumb", alias_target=""}
    result.color_token_provenance[29] = alicorn.Style_Token_Provenance{id=30, name="scratchpad.cool.scrollbar_track", alias_target=""}
    result.color_token_provenance[30] = alicorn.Style_Token_Provenance{id=31, name="scratchpad.cool.selection", alias_target=""}
    result.color_token_provenance[31] = alicorn.Style_Token_Provenance{id=32, name="scratchpad.cool.semantic_focus", alias_target=""}
    result.color_token_provenance[32] = alicorn.Style_Token_Provenance{id=33, name="scratchpad.cool.subtle_surface", alias_target=""}
    result.color_token_provenance[33] = alicorn.Style_Token_Provenance{id=34, name="scratchpad.cool.success", alias_target=""}
    result.color_token_provenance[34] = alicorn.Style_Token_Provenance{id=35, name="scratchpad.cool.surface", alias_target=""}
    result.color_token_provenance[35] = alicorn.Style_Token_Provenance{id=36, name="scratchpad.cool.text", alias_target=""}
    result.color_token_provenance[36] = alicorn.Style_Token_Provenance{id=37, name="scratchpad.cool.window_background", alias_target=""}
    result.length_token_provenance = make([]alicorn.Style_Token_Provenance, 1, allocator)
    result.length_token_provenance[0] = alicorn.Style_Token_Provenance{id=1, name="scratchpad.cool.editor_padding", alias_target=""}
    result.extension_color_role_provenance = make([]alicorn.Style_Extension_Color_Role_Provenance, 1, allocator)
    result.extension_color_role_provenance[0] = alicorn.Style_Extension_Color_Role_Provenance{role=alicorn.Style_Extension_Color_Role_ID(u64(7926949792708367841)), name="app.scratchpad.editor.paper_surface"}
    result.extension_length_role_provenance = make([]alicorn.Style_Extension_Length_Role_Provenance, 1, allocator)
    result.extension_length_role_provenance[0] = alicorn.Style_Extension_Length_Role_Provenance{role=alicorn.Style_Extension_Length_Role_ID(u64(1169174812364479353)), name="app.scratchpad.editor.padding"}
    return result
}

scratchpad_cool_light_theme_materials :: [0]alicorn.Style_Material_Definition{
}

scratchpad_cool_light_theme_destroy :: proc(value: ^alicorn.Style_Theme, allocator := context.allocator) {
    if value == nil { return }
    // Provenance strings are static generated literals; only their slices are owned.
    delete(value.color_tokens, allocator)
    delete(value.length_tokens, allocator)
    delete(value.extension_color_roles, allocator)
    delete(value.extension_length_roles, allocator)
    delete(value.color_token_provenance, allocator)
    delete(value.length_token_provenance, allocator)
    delete(value.extension_color_role_provenance, allocator)
    delete(value.extension_length_role_provenance, allocator)
    value.color_tokens = nil
    value.length_tokens = nil
    value.extension_color_roles = nil
    value.extension_length_roles = nil
    value.color_token_provenance = nil
    value.length_token_provenance = nil
    value.extension_color_role_provenance = nil
    value.extension_length_role_provenance = nil
}
